### ISSUE TITLE
Any documentation provided and Obfuscated Code ?

### ISSUE THREAD

**Issue by Sanix-Darker** [Elyft/elyft-compressor#1]
Buddy... like, seriously..., if you want to share a source code share it properly, if you don't want so, don't share it! How can you share an Obfuscated source code as the core of your app, how can we use your application if we want to use or contribute ? how can we integrate it anything provide !

**Comment by Elyft** [comment]
Hello the code is not obfuscated but compressed and it's normal beacause it's the demo project.
The documentation of the library will come ASAP

**Comment by Sanix-Darker** [comment]
The simple fact that it's minimized it's a real problem, demo project or not doesn't really matter, the demo should be more comment than the final version.... i mean, where is comments ? About what the code is working ? if you try to share a project, make sure to share the complete and readable code(in development mode) + the minify/obfuscated version (for production mode). Hope the core will be comment too, thanks for reply!

**Comment by ishigo1987** [comment]
My code don't need to be comment it's very obvious and easy.
By the way Thank you for your advices

**Comment by Sanix-Darker** [comment]
Your code is OBFUSCATED MAN, OBFUSCATED !
That's the problem !
And yes Comments are needed, you're implementing a kind of "Hermite algorithm", the less you can do is to comment what you have done !

i don't know if you realize the difference between minimize and obfuscate,
you can not have in your code a section like this:
```
var p=4*(u+r*d),z=0,M=0,F=0,I=0,J=0,B=0,C=r*t,
```
and tell is not an obfuscated code man ! Otherwise is a really bad way to name variables.
